### ISSUE TITLE
New Version for 2.2 or above

### ISSUE THREAD

**Issue by Wooobee** [traels/spree-promotion-roles-rule#2]
Hi,

do you plan to update your Spree Extensions for newer Version of Spree?

That would be awesome!

Best regards,
Manuel

**Comment by traels** [comment]
Yes, I am planing on updating this next week

   kh
Simon Træls Ravn
Sent from my iPhone

**Comment by Wooobee** [comment]
Wow cool! I love to hear that! Many thanks!
Manuel

**Comment by traels** [comment]
Hi

Should be ready now, let me know if you have trouble, the test suite is not that rich yet :)

> On 18 Oct 2014, at 19:18, Wooobee notifications@github.com wrote:
> 
> Wow cool! I love to hear that! Many thanks!
> Manuel
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/traels/spree-promotion-roles-rule/issues/2#issuecomment-59622286.

med venlig hilsen / best regards / Mit freundlichen Grüßen

Simon Træls Ravn
CS2|software
+45 2267 1277
cs2@cs2.dk

(alle priser er excl. 25% moms, all prices mentioned are without 25% danish VAT)

**Comment by Wooobee** [comment]
Hey,

many thanks for the effort I will test it tomorrow!

Best regards form Germany,
Manuel
